default_install_hook_types: [pre-commit, commit-msg, pre-push]
exclude: (.*\.sln|.*\.vcxproj|.*\.vcxproj.filters)
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: "v14.0.6"
    hooks:
      - id: clang-format

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.34.0
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages: [push]
